version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pyramid
      POSTGRES_PASSWORD: pyramid
      POSTGRES_DB: pyramid
    ports:
      - '5432:5432'
    volumes:
      - pyramid_pg_data:/var/lib/postgresql/data
volumes:
  pyramid_pg_data:
